In [2]:
import numpy as np
import collections

In [139]:
data = collections.deque(maxlen=7)

In [140]:
data.append((0, 0, 10, 10))
data.append((2, 2, 10, 10))
data.append((0, 0, 10, 10))
data.append((2, 2, 10, 10))
data.append((0, 0, 10, 10))
data.append((2, 2, 10, 10))
data.append((0, 0, 10, 10))
data = np.array(data, dtype=np.float64)

In [141]:
data

array([[ 0.,  0., 10., 10.],
       [ 2.,  2., 10., 10.],
       [ 0.,  0., 10., 10.],
       [ 2.,  2., 10., 10.],
       [ 0.,  0., 10., 10.],
       [ 2.,  2., 10., 10.],
       [ 0.,  0., 10., 10.]])

In [142]:
data[:, 0] += data[:, 2]/2
data[:, 1] += data[:, 3]/2
tracked_centers = data[:, :2]  # Isolate (xc, yc)
tracked_centers

array([[5., 5.],
       [7., 7.],
       [5., 5.],
       [7., 7.],
       [5., 5.],
       [7., 7.],
       [5., 5.]])

In [143]:
overall_speed = np.diff(tracked_centers, axis=0)  # Get all the speed vectors
overall_speed

array([[ 2.,  2.],
       [-2., -2.],
       [ 2.,  2.],
       [-2., -2.],
       [ 2.,  2.],
       [-2., -2.]])

In [144]:
overall_speed = np.mean(overall_speed, axis=0)  # Calculate the mean speed vectors (last minus first basically)
overall_speed

array([0., 0.])

In [145]:
overall_speed = np.linalg.norm(overall_speed)  # Get the norm of that mean vector
overall_speed

0.0